### ISSUE TITLE
dataStream object is missing 

### ISSUE THREAD

**Issue by Gampesh** [googleapis/nodejs-analytics-admin#223]
https://github.com/googleapis/nodejs-analytics-admin/blob/23419288e37ce931b72bbeb3e5f6d229f1b249fa/samples/generated/v1beta/analytics_admin_service.update_data_stream.js#L50

Above line in request object only updateMask is passed but updated dataStream object is missing. 
```
const request = {
      updateMask,
    }; 
```
should be

```
const request = {
                dataStream,
                updateMask,
            }; 
```

**Comment by sofisl** [comment]
Hi @Gampesh, this would generally mean that the dataStream parameter is not required. In your experience using the library, is that the case? If it is required, please open an issue saying so in `google-cloud-node`, since this repo is being migrated over there. Thank you!
