### ISSUE TITLE
How to create a new account?

### ISSUE THREAD

**Issue by mrgoonie** [googleapis/nodejs-analytics-admin#62]
I found this documentation about Account creation: https://googleapis.dev/nodejs/analytics-admin/latest/google.analytics.admin.v1alpha.Account.html#.create

But I can't find any Account class in the package.

When I list for current accounts the library gives me an empty array.

**Comment by sofisl** [comment]
Hi @mrgoonie, you may need to create a ticket to request an account: https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/accounts/provisionAccountTicket

We also have [these docs](https://developers.google.com/analytics/devguides/config/admin/v1#account_management) for further reference.

**Comment by mrgoonie** [comment]
Thank you for the prompt response, @sofisl . That's very helpful.
